apiVersion: v1
data:
  platformsh-backup.yml: |
    platformsh_backup:
      debug: {{ .Values.platformsh_backup.config.debug | quote }}
      {{- with .Values.platformsh_backup.config.sources }}
      sources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.platformsh_backup.config.remotes }}
      remotes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.platformsh_backup.config.backups }}
      backups:
        {{- toYaml . | nindent 8 }}
      {{- end }}

kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ template "platformsh-backup.fullname" . }}-config

